version: '3.8'

services:
  # kafka:
    # image: wurstmeister/kafka:2.13-2.8.1
    # ports:
      # - "9092:9092"
    # environment:
      # KAFKA_ADVERTISED_HOST_NAME: localhost
      # KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_CREATE_TOPICS: "test:1:1"
    # depends_on:
      # - zookeeper

  # zookeeper:
    # image: wurstmeister/zookeeper:3.4.6
    # ports:
      # - "2181:2181"

  #mssql:
  #  image: mcr.microsoft.com/mssql/server:2019-latest
  #  ports:
  #    - "1433:1433"
  #  environment:
  #    - SA_PASSWORD:YourPassword123
  #    - ACCEPT_EULA:Y
  #    - TZ=America/Sao_Paulo
  #  volumes:
  #    - "./tests/IntegrationTests/scripts/:/scripts/"
  #  command:
  #    - /bin/bash
  #    - -c
  #    - |
  #      /opt/mssql/bin/sqlserver &
  #      sleep 40
  #      /opt/mssql-tools/bin/sqlcmd -U sa -P YourPassword123 -l 30 -e -i /scripts/01.Create_Database.sql
  #      /opt/mssql-tools/bin/sqlcmd -U sa -P YourPassword123 -l 30 -e -i /scripts/02.Tabelas.sql
  #      sleep infinity


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "MySuper@StrongPassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./tests/IntegrationTests/scripts:/scripts
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & sleep 30s \
        && /opt/mssql-tools/bin/sqlcmd -U sa -P MySuper@StrongPassword -l 30 -e -i /scripts/01.Create_Database.sql
        sleep infinity
  # reis:
    # image: redis:latest
    # ports:
      # - "6379:6379"

  # kibana:
    # image: docker.elastic.co/kibana/kibana:7.16.2
    # ports:
      # - "5601:5601"
    # depends_on:
      # - elasticsearch
    # environment:
      # ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

  # elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    # ports:
      # - "9200:9200"
      # - "9300:9300"
    # environment:
      # discovery.type: single-node
